
CREATE DATABASE IF NOT EXISTS hubgreen
	CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE hubgreen;

CREATE TABLE estados(
	SGUF CHAR(2) PRIMARY KEY NOT NULL,
    NMUF VARCHAR(20) NOT NULL
);

CREATE TABLE cidades(
	CDCIDADE BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NMCIDADE VARCHAR(50) NOT NULL,
    SGUF CHAR(2) NOT NULL,

    CONSTRAINT FK_CIDADES_ESTADO
		FOREIGN KEY (SGUF)
        REFERENCES estados(SGUF)
        ON UPDATE CASCADE
);

CREATE TABLE categorias(
	CDCATEGORIA BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NMCATEGORIA VARCHAR(60) NOT NULL,
    DSCATEGORIA VARCHAR(200),

    UNIQUE KEY UK_CATEGORIA_NOME (NMCATEGORIA)
);

SET SESSION sql_mode = (SELECT CONCAT(@@sql_mode, ',NO_AUTO_VALUE_ON_ZERO'));
INSERT IGNORE INTO categorias (CDCATEGORIA, NMCATEGORIA) VALUES (0, 'Sem Categoria');

CREATE TABLE expositores(
	CDEXPOSITOR BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NMEXPOSITOR VARCHAR(100),
    BIOEXPOSITOR TEXT
);

CREATE TABLE eventos(
	CDEVENTO BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NMEVENTO VARCHAR(100) NOT NULL,
    LOCALEVENTO VARCHAR(200) NOT NULL,
    CDCIDADE BIGINT UNSIGNED NOT NULL,
    DTHREVENTO DATETIME NOT NULL,
    STEVENTO ENUM('MARCADO', 'EM_ANDAMENTO', 'FINALIZADO', 'CANCELADO') NOT NULL DEFAULT 'MARCADO',
    DSEVENTO TEXT,

    FOREIGN KEY (CDCIDADE) REFERENCES cidades (CDCIDADE) ON UPDATE CASCADE
);

CREATE TABLE participacoes(
	CDPARTICIPACAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CDEVENTO BIGINT UNSIGNED NOT NULL,
    CDEXPOSITOR BIGINT UNSIGNED NOT NULL,
    STPARTICIPACAO ENUM('ATIVO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO',

    PRIMARY KEY (CDPARTICIPACAO),

    UNIQUE KEY UK_EVENTO_EXPOSITOR (CDEVENTO, CDEXPOSITOR),

    CONSTRAINT FK_PARTICIPACAO_EVENTO
		FOREIGN KEY (CDEVENTO)
        REFERENCES eventos (CDEVENTO)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_PARTICIPACAO_EXPOSITOR
		FOREIGN KEY (CDEXPOSITOR)
        REFERENCES expositores (CDEXPOSITOR)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE expimagens(
	CDEXPIMAGEM BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CDEXPOSITOR BIGINT UNSIGNED NOT NULL,
    CAMINHOEXPIMAGEM VARCHAR(500) NOT NULL,
    DTEXPIMAGEM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IDEXPIMAGEM ENUM('perfil', 'outras') NOT NULL DEFAULT 'outras',

    CONSTRAINT FK_EXPIMAGENS_EXPOSITOR
		FOREIGN KEY (CDEXPOSITOR)
        REFERENCES expositores (CDEXPOSITOR)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE produtos(
	CDPRODUTO BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NMPRODUTO VARCHAR(50) NOT NULL,
    DSPRODUTO TEXT NULL,
    CDEXPOSITOR BIGINT UNSIGNED NOT NULL,
    CAMINHOIMAGEM VARCHAR(500) NULL,
    VALOR DECIMAL(12, 2) NULL,
    CDCATEGORIA BIGINT UNSIGNED NOT NULL DEFAULT 0,

    CONSTRAINT FK_PRODUTOS_EXPOSITOR
		FOREIGN KEY (CDEXPOSITOR)
        REFERENCES expositores (CDEXPOSITOR)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_PRODUTOS_CATEGORIA
		FOREIGN KEY (CDCATEGORIA)
        REFERENCES categorias (CDCATEGORIA)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE evimagens(
	CDEVIMAGEM BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CDEVENTO BIGINT UNSIGNED NOT NULL,
	CAMINHOEVIMAGEM VARCHAR(500) NOT NULL,
    DTEVIMAGEM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_EVIMAGENS_EVENTO
		FOREIGN KEY (CDEVENTO)
        REFERENCES eventos (CDEVENTO)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);